<?xml version="1.0"?>
<robot name="robot_summer" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find robot_model)/urdf/wheel.urdf.xacro" />
    <!--xacro:include filename="$(find robot_model)/urdf/axel.urdf.xacro" />
    <xacro:include filename="$(find robot_model)/urdf/zed.urdf.xacro" /-->
    <!--xacro:include filename="$(find robot_model)/urdf/lidar.gazebo" /-->
    <property name="M_PI" value="3.14159"/>

    <!-- Wheel Mounting Positions -->
    <!--xacro:property name="wheelbase" value="1.3589" />
    <xacro:property name="track" value="0.53" />
    <xacro:property name="wheel_vertical_offset" value="0.0635" /-->

    <property name="chassis_base_vertical_offset" value="0.02032" />

    <!-- Base Size: center chassis link size.  -->
    <property name="chassis_base_x_size" value="0.1651" />
    <property name="chassis_base_y_size" value="0.10795" />
    <property name="chassis_base_z_size" value="0.001" />

    <property name="axel_length" value="0.15804" />
    <property name="axel_radius" value="0.005" />

    <!-- shell Size: center chassis link size.  -->
    <property name="shell_1_x_size" value="0.1651" />
    <property name="shell_1_y_size" value="0.10795" />
    <property name="shell_1_z_size" value="0.08255" />
    <property name="shell_1_x_loc" value="0" />
    <property name="shell_1_y_loc" value="0" />
    <property name="shell_1_z_loc" value="0.041275" />

    <!-- shell Size: center chassis link size.  -->
    <property name="shell_2_x_size" value="0.06096" />
    <property name="shell_2_y_size" value="0.10795" />
    <property name="shell_2_z_size" value="0.1337818" />
    <property name="shell_2_x_loc" value="0.05207" />
    <property name="shell_2_y_loc" value="0" />
    <property name="shell_2_z_loc" value="0.0668909" />

    <!-- shell Size: center chassis link size.  -->
    <property name="shell_3_x_size" value="0.09017" />
    <property name="shell_3_y_size" value="0.24765" />
    <property name="shell_3_z_size" value="0.0127" />
    <property name="shell_3_x_loc" value="-0.037465" />
    <property name="shell_3_y_loc" value="0" />
    <property name="shell_3_z_loc" value="0.047625" />

    <!-- shell Size: center chassis link size.  -->
    <property name="shell_4_x_size" value="0.06000" />
    <property name="shell_4_y_size" value="0.24795" />
    <property name="shell_4_z_size" value="0.005334" />
    <property name="shell_4_x_loc" value="0.06096" />
    <property name="shell_4_y_loc" value="0" />
    <property name="shell_4_z_loc" value="0.1337818" />


    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.021336" />
    <xacro:property name="wheel_radius" value="0.04191" />
    <property name="wheel_vertical_offset" value="0.085" />
    <xacro:macro name="robot_summer"/>

    <!--link name="chassis_footprint"/-->
    <link name="base_link"/>
    <link name="chassis_link">
        <collision name='collision'>
            <geometry>
                <box size="${chassis_base_x_size} ${chassis_base_y_size} ${chassis_base_z_size}"/>
            </geometry>
        </collision>

        <visual name='visual'>
            <geometry>
                <box size="${chassis_base_x_size} ${chassis_base_y_size} ${chassis_base_z_size}"/>
            </geometry>
            <material name="grey">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
    </link>
    <joint name="chassis_baselink_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0.04191 0 0" rpy="0 0 0"/>
    </joint>
    <!--joint name="chassis_footprint_joint" type="fixed">
        <parent link="chassis_footprint"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 ${chassis_base_vertical_offset}" rpy="0 0 0"/>
    </joint-->

    <link name="shell_link_1">
        <collision name='collision'>
            <geometry>
                <box size="${shell_1_x_size} ${shell_1_y_size} ${shell_1_z_size}"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <box size="${shell_1_x_size} ${shell_1_y_size} ${shell_1_z_size}"/>
            </geometry>
            <material name="light_grey">
                <color rgba="0.2 0.2 0.2 1"/>
            </material>
        </visual>
    </link>
    <joint name="chassis_shell_1_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="shell_link_1"/>
        <origin xyz="${shell_1_x_loc} ${shell_1_y_loc} ${shell_1_z_loc}" rpy="0 0 0"/>
    </joint>
    <link name="shell_link_2">
        <collision name='collision'>
            <geometry>
                <box size="${shell_2_x_size} ${shell_2_y_size} ${shell_2_z_size}"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <box size="${shell_2_x_size} ${shell_2_y_size} ${shell_2_z_size}"/>
            </geometry>
            <material name="light_grey">
                <color rgba="0.2 0.2 0.2 1"/>
            </material>
        </visual>
    </link>
    <joint name="chassis_shell_2_joint" type="fixed">
        <parent link="shell_link_1"/>
        <child link="shell_link_2"/>
        <origin xyz="${shell_2_x_loc} ${shell_2_y_loc} ${shell_2_z_loc}" rpy="0 0 0"/>
    </joint>
    <link name="shell_link_3">
        <collision name='collision'>
            <geometry>
                <box size="${shell_3_x_size} ${shell_3_y_size} ${shell_3_z_size}"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <box size="${shell_3_x_size} ${shell_3_y_size} ${shell_3_z_size}"/>
            </geometry>
            <material name="light_grey">
                <color rgba="0.2 0.2 0.2 1"/>
            </material>
        </visual>
    </link>
    <joint name="chassis_shell_3_joint" type="fixed">
        <parent link="shell_link_1"/>
        <child link="shell_link_3"/>
        <origin xyz="${shell_3_x_loc} ${shell_3_y_loc} ${shell_3_z_loc}" rpy="0 0 0"/>
    </joint>
    <link name="shell_link_4">
        <collision name='collision'>
            <geometry>
                <box size="${shell_4_x_size} ${shell_4_y_size} ${shell_4_z_size}"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <box size="${shell_4_x_size} ${shell_4_y_size} ${shell_4_z_size}"/>
            </geometry>
            <material name="light_grey">
                <color rgba="0.2 0.2 0.2 1"/>
            </material>
        </visual>
    </link>
    <joint name="chassis_shell_4_joint" type="fixed">
        <parent link="shell_link_1"/>
        <child link="shell_link_4"/>
        <origin xyz="${shell_4_x_loc} ${shell_4_y_loc} ${shell_4_z_loc}" rpy="0 0 0"/>
    </joint>
    <link name="axel_link">
        <collision name='collision'>
            <geometry>
                <cylinder length="${axel_length}" radius="${axel_radius}"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <cylinder length="${axel_length}" radius="${axel_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
    </link>
    <joint name="axel_shell_1_joint" type="fixed">
        <parent link="shell_link_1"/>
        <child link="axel_link"/>
        <origin xyz="-0.04191 0 -0.019685" rpy="${M_PI/2} 0 0"/>
    </joint>
    <xacro:robot_wheel wheel_prefix="left" axel_prefix="axel_link">
        <origin xyz="0 0  ${axel_length/2}" rpy="${M_PI/2} 0 0" />
    </xacro:robot_wheel>
    <xacro:robot_wheel wheel_prefix="right" axel_prefix="axel_link">
        <origin xyz="0 0 -${axel_length/2}" rpy="${M_PI/2} 0 0" />
    </xacro:robot_wheel>
    <!--xacro:robot_zed zed_prefix="ZED" zed_parent_link="shell_link">
        <origin xyz="${shell_base_x_size/2+lidar_radius} 0 ${shell_base_z_size/6}" rpy="0 0 0"/>
    </xacro:robot_zed-->

    <link name="camera_link"/>
    <link name="camera_left_link">
        <collision name='collision'>
            <geometry>
                <box size="0.015 0.09398 0.03556"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <mesh filename="package://robot_model/meshes/Logitech_C920.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0.05 -0.005" rpy="${M_PI/2} 0 -${M_PI/2} "/>
        </visual>
    </link>
    <joint name="camera_joint" type="fixed">
        <parent link="shell_link_4"/>
        <child link="camera_link"/>
        <!--origin xyz="${shell_4_x_size/2} 0.0773862 0.01778" rpy="0 -0.209439 0"/-->
        <!--origin xyz="${shell_4_x_size/2} 0.0773862 0.01778" rpy="0 0 0"/-->
        <!--origin xyz="${shell_4_x_size/2} 0 0.01778" rpy="${M_PI/2} ${M_PI/2} 0"/-->
        <origin xyz="${shell_4_x_size/2} 0 0.01778" rpy="0 ${M_PI/2} 0 "/>
    </joint>
    <joint name="camera_left_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_left_link"/>
        <!--origin xyz="${shell_4_x_size/2} 0.0773862 0.01778" rpy="0 -0.209439 0"/-->
        <origin xyz="0 0.0773862 0" rpy="0 0 -${M_PI/2}"/>
    </joint>
    <link name="camera_right_link">
        <collision name='collision'>
            <geometry>
                <box size="0.015 0.09398 0.03556"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <mesh filename="package://robot_model/meshes/Logitech_C920.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0.05 -0.005" rpy="+${M_PI/2} 0 -${M_PI/2} "/>
        </visual>
    </link>
    <joint name="camera_right_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_right_link"/>
        <origin xyz="0 -0.0773862 0" rpy="0 0 -${M_PI/2}"/>
    </joint>
    <link name="raspberry_link_1">
        <collision name='collision'>
            <geometry>
                <box size="0.8560 0.5650 0.1"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <mesh filename="package://robot_model/meshes/Raspberry_Pi_3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>
    <joint name="raspberry_joint_1" type="fixed">
        <parent link="shell_link_3"/>
        <child link="raspberry_link_1"/>
        <origin xyz="-0.05 0.0406325  0.005" rpy="0 0 0"/>
    </joint>
    <link name="raspberry_link_2">
        <collision name='collision'>
            <geometry>
                <box size="0.8560 0.5650 0.1"/>
            </geometry>
        </collision>
        <visual name='visual'>
            <geometry>
                <mesh filename="package://robot_model/meshes/Raspberry_Pi_3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>
    <joint name="raspberry_joint_2" type="fixed">
        <parent link="shell_link_3"/>
        <child link="raspberry_link_2"/>
        <origin xyz="+0.05 -0.0406325  0.005" rpy="0 0 ${M_PI}"/>
    </joint>


</robot>
